# [WebParam]
# specificUrlLink=category=road-bikes/#
# paramsOnUrl=category=road,type=html
#
mainUrl: https://www.canyon.com/fr/factory-outlet/
ajaxUrl: ajax/articles.html
urlParam:
    category: road
    type: html
#Canyon specific parameter
#
filter:
    #serie:             
    size: S
    #year:         
    year: [2010,2011]
#Email parameter
email:
    from: fdaligand.insidefr.com
    to: florent.daligand@gmail.com        

    
